language: python
python:
  - 2.7
os:
  - linux
before_install:
  - chmod +x devtools/travis-ci/chimera.sh
  # Chimera:
  - devtools/travis-ci/chimera.sh
install:
  # Install package
  - pip install -i https://test.pypi.org/simple/ compare-equal
script:
  # Check packages
  - $HOME/chimera/bin/chimera --nogui --silent tests/mol_test.py
  - $HOME/chimera/bin/chimera --nogui --silent tests/pdb_test.py
